### ISSUE TITLE
Cannot Provide a New Timestamp to correct actual log times

### ISSUE THREAD

**Issue by simonireilly** [coralogix/nodejs-coralogix-sdk#12]
When logging my CDN, I push coralogix logs to s3, then consume through a lambda.

I want to replace the timestamp created in the lambda, with the timestamp forwarded from my CDN.

https://github.com/coralogix/nodejs-coralogix-sdk/blob/0be7d2c7a5a57c0d8b6e3268c1dc520b1e6187fc/src/entities/log.ts#L110-L123

Here, in the above constructor, line 111, I want to supply an over-ride to the timestamp as an optional attr.

`this.timestamp = data.timestamp || Date.now();`

**Comment by EldarAliiev** [comment]
https://github.com/coralogix/nodejs-coralogix-sdk/blob/d87d3c16a8a17e7666e6c5c59fcf073188491eda/dist/entities/log.js#L32-L34
